### ISSUE TITLE
About evaluating models

### ISSUE THREAD

**Issue by cyk990422** [NetEase-GameAI/ProPose#12]
Is the demo model you open source the evaluation model for 3dpw-test in your paper? It seems that I used the same evaluation code of pare and hmr, and the bbox information provided by 3dpw-test got a result of 82.2 (MPJPE). This is quite different from the 68.3 in the article.

**Comment by raypine** [comment]
No. 1) The ratio of 3DPW in the training set is low to improve the generalization ability. The evaluated model has a large ratio of 3DPW in the mixed dataset. 2) See the [discussion.md](https://github.com/NetEase-GameAI/ProPose/blob/main/discussion.md) for the difference. To deal with truncation, we replace the heatmap-based keypoint branch with the regression-based keypoint strategy. Since the 3DPW has almostly no truncation, it's better to use the heatmap-based method. 3) Following HybrIK, the translation of human is from their preprocessed file and is different from our camera branch for a fair comparison.
